### ISSUE TITLE
File Transfer

### ISSUE THREAD

**Issue by LostSoulFly** [bigqio/bigq#1]
First, let me say that I've written very, very small things in c# and I'm looking to expand my knowledge.

Are there any plans to implement file transfers between users? What would be the best way to handle this (assuming peer to peer isn't an viable option)?

I'd like to create an IM server/client for use by a few departments at my work, and ideally they'd be able to transfer files between each other individually or in a channel/group chat.

I think your work is an excellent starting point for someone with my limited knowledge of the language and I appreciate your work and making it available!

**Comment by jchristn** [comment]
Hi there, thanks for your note.  For most objects you can transfer them in a single message since the framing will take care of the amount of data to read - you would just need your own message structure to indicate that the payload was a file.  For larger objects there would definitely need to be an overlay that would handle breaking the object apart and sending in multiple messages (on the sending side) and reconstruction (on the receiving side).  Implementing this for a one-to-one scenario would be straight forward; doing this in a one-to-many (i.e. channel) scenario would be rather difficult.  

If I were to implement this I'd actually do the file transfer piece in the chat app rather than in the service or client library.  The primary reason is that I wouldn't want to add the re-transfer or storage burden to the libraries themselves.  That would get ugly.  The libraries are designed for sending sync or async messages and not really designed for managing multipart transfers.

Cheers!
